CREATE DATABASE IF NOT EXISTS carteira_digital CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE carteira_digital;
CREATE TABLE usuarios (id_usuario INT AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(120) NOT NULL, email VARCHAR(150) NOT NULL UNIQUE, senha_hash VARCHAR(255) NOT NULL, cor_carteira VARCHAR(7) NOT NULL DEFAULT '#2b5c8a', data_criacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE contas (id_conta INT AUTO_INCREMENT PRIMARY KEY, id_usuario INT NOT NULL UNIQUE, saldo DECIMAL(12,2) NOT NULL DEFAULT 0.00, data_criacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT chk_saldo_nao_negativo CHECK (saldo >= 0), CONSTRAINT fk_contas_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE transacoes (id_transacao INT AUTO_INCREMENT PRIMARY KEY, id_conta_origem INT NOT NULL, id_conta_destino INT NOT NULL, valor DECIMAL(12,2) NOT NULL, data_transacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, status VARCHAR(20) NOT NULL DEFAULT 'concluida', CONSTRAINT chk_valor_positivo CHECK (valor > 0), CONSTRAINT chk_status_valido CHECK (status IN ('concluida','pendente','cancelada')), CONSTRAINT chk_contas_diferentes CHECK (id_conta_origem <> id_conta_destino), CONSTRAINT fk_transacoes_origem FOREIGN KEY (id_conta_origem) REFERENCES contas(id_conta), CONSTRAINT fk_transacoes_destino FOREIGN KEY (id_conta_destino) REFERENCES contas(id_conta)) ENGINE=InnoDB;
CREATE TABLE logs_acesso (id_log INT AUTO_INCREMENT PRIMARY KEY, id_usuario INT NOT NULL, data_login DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ip_origem VARCHAR(45), CONSTRAINT fk_logs_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE INDEX idx_transacoes_origem ON transacoes(id_conta_origem); CREATE INDEX idx_transacoes_destino ON transacoes(id_conta_destino); CREATE INDEX idx_logs_usuario ON logs_acesso(id_usuario);
CREATE OR REPLACE VIEW vw_extrato AS SELECT t.id_transacao, uo.nome usuario_origem, ud.nome usuario_destino, t.valor, t.data_transacao, t.status FROM transacoes t JOIN contas co ON co.id_conta=t.id_conta_origem JOIN contas cd ON cd.id_conta=t.id_conta_destino JOIN usuarios uo ON uo.id_usuario=co.id_usuario JOIN usuarios ud ON ud.id_usuario=cd.id_usuario;
DELIMITER $$
CREATE TRIGGER trg_valida_saldo_antes_transacao BEFORE INSERT ON transacoes FOR EACH ROW BEGIN DECLARE saldo_atual DECIMAL(12,2); SELECT saldo INTO saldo_atual FROM contas WHERE id_conta=NEW.id_conta_origem; IF saldo_atual < NEW.valor THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Saldo insuficiente para realizar a transferência.'; END IF; END$$
CREATE PROCEDURE sp_transferir(IN p_id_conta_origem INT, IN p_id_conta_destino INT, IN p_valor DECIMAL(12,2)) BEGIN START TRANSACTION; INSERT INTO transacoes(id_conta_origem,id_conta_destino,valor,status) VALUES(p_id_conta_origem,p_id_conta_destino,p_valor,'concluida'); UPDATE contas SET saldo=saldo-p_valor WHERE id_conta=p_id_conta_origem; UPDATE contas SET saldo=saldo+p_valor WHERE id_conta=p_id_conta_destino; COMMIT; END$$
DELIMITER ;
-- Consultas complexas: SELECT * FROM vw_extrato; SELECT u.nome,c.saldo FROM usuarios u JOIN contas c ON c.id_usuario=u.id_usuario; SELECT ud.nome,SUM(t.valor) total_recebido FROM transacoes t JOIN contas c ON c.id_conta=t.id_conta_destino JOIN usuarios ud ON ud.id_usuario=c.id_usuario GROUP BY ud.id_usuario,ud.nome;
